WebsterWebApp/Controllers/UserAuthController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebsterWebApp.Data;
using WebsterWebApp.Models;
using Microsoft.AspNetCore.Http;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;
using WebsterWebApp.Areas.Admin.Models;
using System.IO;

namespace WebsterWebApp.Controllers
{
    public class UserAuthController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ApplicationDbContext _context;
        private readonly Repository.IMailService _mailServices;
        public readonly IConfiguration _configuration;


        public UserAuthController(UserManager<ApplicationUser> _userManager, SignInManager<ApplicationUser> _signInManager, ApplicationDbContext _context, Repository.IMailService _mailServices, IConfiguration _configuration) 
        {
            this._context = _context;
            this._signInManager = _signInManager;
            this._userManager = _userManager;
            this._mailServices = _mailServices;
            this._configuration = _configuration;
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel loginModel)
        {
            Services.Mail mail = new Services.Mail();
            
            //await mail.SendMail(toMail, subject, body);

            //-------------------------------------------------------------

            //Set default login valid message to 'true', if it match, then the msg
            //is changed to empty, else it display Invalid login attempt.
            loginModel.LoginInValid = "true";

            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(loginModel.Email,
                                                                     loginModel.Password,
                                                                     loginModel.RememberMe,
                                                                     lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    HttpContext.Session.SetString("Mail", loginModel.Email);

                    loginModel.LoginInValid = "";
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt");
                }
            }
            return PartialView("_UserLoginPartial", loginModel);
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout(string returnUrl = null)
        {
            //HttpContext.Session.Remove("Mail");
            //return BadRequest(HttpContext.Session.GetString("Mail"));


            await _signInManager.SignOutAsync();

            if (returnUrl != null)
            {
           
                return LocalRedirect(returnUrl);
            }
            else
            {
                HttpContext.Session.Remove("Mail");
                HttpContext.Session.Remove("count");
                return RedirectToAction("Index", "Home");
            }
        }

        [AllowAnonymous]
        public async Task<bool> UserNameExists(string userName) 
        {
            bool userNameExists = await _context.Users.AnyAsync(u => u.UserName.ToUpper() == userName.ToUpper());
            if (userNameExists == true) 
            {
                return true;
            }
            else { return false; }
        }

        private void AddErrorsToModelState(IdentityResult result) 
        {
            foreach (var error in result.Errors) 
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }

        private string GenerateJwtToken(User user)
        {
            var tokenHandler = new JwtSecurityTokenHandler();
            var key = Encoding.ASCII.GetBytes(_configuration.GetSection("AppSetting:Secret").Value);

            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Subject = new ClaimsIdentity(new Claim[]{
                    new Claim(ClaimTypes.NameIdentifier, user.Email.ToString()),
                    new Claim(ClaimTypes.Name, user.Email)
                }),
                Expires = DateTime.UtcNow.AddDays(1),
                SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha256Signature)
            };

            var token = tokenHandler.CreateToken(tokenDescriptor);
            return tokenHandler.WriteToken(token);
        }

        [Authorize(Roles = "User,Admin")]
        public IActionResult PersonalPage()
        {


            var exam = _context.Exams.ToList();

            var ExamUserId = _context.Users.SingleOrDefault(t => t.UserName.Equals(HttpContext.Session.GetString("Mail"))).Id;

            var list = _context.ExamUsers.Where(s => s.UserId.Equals(ExamUserId)).ToList();


            var ds1 = (from s in list
                       join t in exam
                       on s.ExamId.ToString() equals t.ExamId.ToString()
                       select t
                      ).ToList();
            List<Models.Exam> examuser = new List<Models.Exam>();
            List<Models.ResultsModel> result = new List<Models.ResultsModel>();


            foreach (var item in ds1)
            {
                var t = _context.Results.SingleOrDefault(t => t.ExamId == item.ExamId && t.IdUser.Equals(ExamUserId) && t.TimeTech != 0);

                if (t != null)
                {
                    examuser.Add(item);
                    result.Add(t);
                }
                else
                {
                }

            }

            ViewBag.ds = examuser.ToArray();
            ViewBag.ds1 = result.ToArray();


            return View();
        }

        [Authorize(Roles = "User,Admin")]
        public IActionResult Changeinfor()
        {
            return View();
        }
        [Authorize(Roles = "User,Admin")]
        [HttpPost]
        public IActionResult Changeinfor(RegistrationModel registrationModel, IFormFile Avatar)
        {
            string id = _userManager.GetUserAsync(User).Result?.Id;
            var res = _context.Users.SingleOrDefault(t => t.Id.Equals(id));
            var s = "";


            if (Avatar != null)
            {
                var filePath = Path.Combine("wwwroot/images/user", Avatar.FileName);
                var stream = new FileStream(filePath, FileMode.Create);
                Avatar.CopyToAsync(stream);
                s = "images/user/" + Avatar.FileName;
            }
            else
            {
                s = res.Avatar;
            }
   

            res.LastName = registrationModel.LastName;
            res.FirstName = registrationModel.FirstName;
            res.PhoneNumber = registrationModel.PhoneNumber;
            res.Avatar = s;

            _context.SaveChanges();

            


            return RedirectToAction("PersonalPage");
        }
    }
}

WebsterWebApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] </title>
    <link href="~/lightbox/lightbox.min.css" rel="stylesheet" />
    <script src="~/lightbox/lightbox-plus-jquery.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="~/images/system/logo.png" alt="Webster" height="200" width="200">
        </div>

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <div style="margin-top:2%; margin-right:10px">
                    <a class="nav-link text-dark" href="/UserAuth/PersonalPage" title="Manage">Hello @User.Identity.Name!</a>
                </div>
                <form class="form-inline" asp-action="Logout" asp-controller="UserAuth" asp-area="">
                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                </form>
            </ul>
        </nav>




        <!-- Navbar Search -->
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4" style="background-color:mediumpurple!important">
            <!-- Brand Logo -->
            <a href="/Admin/Admin/Index" class="brand-link">
                <img src="~/images/system/logo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Webster</span>
            </a>




            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <li class="nav-item menu-open">
                        <a href="#" class="nav-link ">
                            <i class="nav-icon fas fa-user"></i>
                            <p>
                                Account
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a asp-action="UserList" asp-controller="Admin" class="nav-link ">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>User List</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="AdminList" asp-controller="Admin" class="nav-link ">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Admin List</p>
                                </a>
                            </li>
                        </ul>
                    </li>


                    <!-- Add icons to the links using the .nav-icon class
                    with font-awesome or any other icon font library -->
                    <li class="nav-item menu-open">
                        <a href="#" class="nav-link ">
                            <i class="nav-icon fas fa-question"></i>
                            <p>
                                Question
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a asp-action="Index" asp-controller="Question" class="nav-link ">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Question Group</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="Create" asp-controller="Question" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Create Question</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="BatchQuestionUpload" asp-controller="Question" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Upload Question</p>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item menu-open">
                        <a href="#" class="nav-link ">
                            <i class="nav-icon fas fa-diagnoses"></i>
                            <p>
                                Exam
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a asp-action="Index" asp-controller="Exam" class="nav-link ">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Exam List</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="Create" asp-controller="Exam" class="nav-link ">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Create Exam</p>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="/Admin/Statistique/index" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Statistical</p>
                                </a>
                            </li>
                        </ul>
                    </li>

                </ul>
            </nav>
            <!-- /.sidebar-menu -->
            <!-- /.sidebar -->
        </aside>

    
    <div class="content-wrapper">
        <div style="margin-left:30px; margin-top: 10px;" >
            <div class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-10">
                    @RenderBody()
                </div>
            </div>
        </div>

                    
        </div>

        <footer class="main-footer">
            <strong>Copyright &copy; 2021-2022 <a href="https://Webster.tk">Webster</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 1.0
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/dist/js/pages/dashboard.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.js"></script>
    <script src="~/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.js"></script>
    <script src="~/js/UserRegistration.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebsterWebApp/Areas/Admin/Views/Shared/_LayoutQuestion.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] </title>
    <link href="~/lightbox/lightbox.min.css" rel="stylesheet" />
    <script src="~/lightbox/lightbox-plus-jquery.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="~/images/system/logo.png" alt="Webster" height="200" width="200">
        </div>

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <div style="margin-top:2%; margin-right:10px">
                    <a class="nav-link text-dark" href="/UserAuth/PersonalPage" title="Manage">Hello @User.Identity.Name!</a>
                </div>
                <form class="form-inline" asp-action="Logout" asp-controller="UserAuth" asp-area="">
                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                </form>
            </ul>
        </nav>




        <!-- Navbar Search -->
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4" style="background-color:mediumpurple!important">
            <!-- Brand Logo -->
            <a href="/Admin/Admin/Index" class="brand-link">
                <img src="~/images/system/logo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Webster</span>
            </a>




            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <li class="nav-item menu-open">
                        <a href="#" class="nav-link ">
                            <i class="nav-icon fas fa-user"></i>
                            <p>
                                Account
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a asp-action="UserList" asp-controller="Admin" class="nav-link ">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>User List</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="AdminList" asp-controller="Admin" class="nav-link ">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Admin List</p>
                                </a>
                            </li>
                        </ul>
                    </li>


                    <!-- Add icons to the links using the .nav-icon class
                    with font-awesome or any other icon font library -->
                    <li class="nav-item menu-open">
                        <a href="#" class="nav-link ">
                            <i class="nav-icon fas fa-question"></i>
                            <p>
                                Question
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a asp-action="Index" asp-controller="Question" class="nav-link ">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Question Group</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="Create" asp-controller="Question" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Create Question</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="BatchQuestionUpload" asp-controller="Question" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Upload Question</p>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item menu-open">
                        <a href="#" class="nav-link ">
                            <i class="nav-icon fas fa-diagnoses"></i>
                            <p>
                                Exam
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a asp-action="Index" asp-controller="Exam" class="nav-link ">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Exam List</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="Create" asp-controller="Exam" class="nav-link ">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Create Exam</p>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="/Admin/Statistique/index" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Statistical</p>
                                </a>
                            </li>
                        </ul>
                    </li>

                </ul>
            </nav>
            <!-- /.sidebar-menu -->
            <!-- /.sidebar -->
        </aside>

    
    <div class="content-wrapper">
        <div style="margin-left:30px; margin-top: 10px;">
            @RenderBody()
        </div>     
    </div>

        <footer class="main-footer">
            <strong>Copyright &copy; 2021-2022 <a href="https://Webster.tk">Webster</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 1.0
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/dist/js/pages/dashboard.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.js"></script>
    <script src="~/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.js"></script>
    <script src="~/js/UserRegistration.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>