WebsterWebApp/Areas/Admin/Controllers/StatistiqueController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace WebsterWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class StatistiqueController : Controller
    {


        private readonly Data.ApplicationDbContext db;

        public StatistiqueController(Data.ApplicationDbContext db)
        {
            this.db = db;
        }


        public IActionResult Index()
        {

            ViewBag.res = db.Exams.ToList();
            return View();
        }

        public IActionResult Detail(string  ExamId)
        {

            ViewBag.Exam = db.Exams.SingleOrDefault(t => t.ExamId == int.Parse(ExamId));
            ViewBag.user = (from t in db.ExamUsers
                        where t.ExamId == int.Parse(ExamId)
                        join b in db.Users on
                        t.UserId equals b.Id
                        select b).ToArray();
            ViewBag.result = db.Results.Where(t => t.ExamId == int.Parse(ExamId)).ToArray();

            return View();
        }


        public IActionResult Detailuser(string ExamId, string Maill)
        {

    


            string examid = ExamId;

            var ExamUserId = db.Users.SingleOrDefault(t => t.UserName.Equals(Maill)).Id;



            var res = db.Results.SingleOrDefault(t => t.IdUser.Equals(ExamUserId) && t.ExamId == int.Parse(examid));
            string examname = db.Exams.SingleOrDefault(t => t.ExamId == int.Parse(examid)).ExamName;
            string name = db.Users.SingleOrDefault(t => t.Id.Equals(ExamUserId)).FirstName + db.Users.SingleOrDefault(t => t.Id.Equals(ExamUserId)).LastName;

            ViewBag.mail = Maill;
            ViewBag.res = res;
            ViewBag.examname = examname;
            ViewBag.name = name;



            return View();
        }


        public IActionResult Report(string ExamId)
        {

            var users = (from examuser in db.ExamUsers
                      where examuser.ExamId == int.Parse(ExamId)
                      join user in db.Users
                      on examuser.UserId equals user.Id
                      join exam in db.Exams
                      on examuser.ExamId equals exam.ExamId
                      select new
                      {
                          user.FirstName, user.LastName, user.Email,exam.ExamName, user.Id, exam.ExamId
                      }).ToList();


            var results = db.Results.Where(t => t.ExamId == int.Parse(ExamId)).ToList();


            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[13] {
                    new DataColumn("First Name"),
                    new DataColumn("Last Name"),
                    new DataColumn("Mail"),
                    new DataColumn("Exam Name"),
                    new DataColumn("General Knowledge Score"),
                    new DataColumn("General Knowledge Time"),
                    new DataColumn("Math Score"),
                    new DataColumn("Math Time"),
                    new DataColumn("Tech Score"),
                    new DataColumn("Tech Time"),
                    new DataColumn("Exam Date "),
                    new DataColumn("Is Test"),
                    new DataColumn("Is Pass")
            });

            string examname = "";

            for (int i = 0; i < users.Count; i++)
            {
                examname = users[i].ExamName;
                var dataresult = results.SingleOrDefault(t => t.IdUser == users[i].Id && t.ExamId == users[i].ExamId);

                if (dataresult != null)
                {
                    dt.Rows.Add(users[i].FirstName, 
                                users[i].LastName,
                                users[i].Email,
                                users[i].ExamName,
                                dataresult.GKScore,
                                dataresult.TimeGK,
                                dataresult.MathScore,
                                dataresult.TimeMath,
                                dataresult.TechScore,
                                dataresult.TimeTech,
                                dataresult.ExamDate,
                                true,
                                dataresult.IsPass
                                );
                }
                else
                {
                    dt.Rows.Add(users[i].FirstName,
                               users[i].LastName,
                               users[i].Email,
                               users[i].ExamName,
                               "Not Found",
                               "Not Found",
                               "Not Found",
                               "Not Found",
                               "Not Found",
                               "Not Found",
                               "Not Found",
                               true,
                              "Not Found"
                               );
                }


            }


            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);

                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadssheetml.sheet", "Report "+ examname + ".xlsx");
                }

            }


          
        }

    }
}

WebsterWebApp/Areas/Admin/Views/Statistique/Detail.cshtml
@{
    ViewData["Title"] = ViewBag.Exam.ExamName + " Detail";

    var a = ViewBag.result;
    var countthi = a.Length;

    var countthitotal = ViewBag.user.Length;

    int count = 0;
    for (int k = 0; k < a.Length; k++)
    {
        if (a[k].IsPass == true)
        {
            count += 1;
        }
    }

    int i = 0;
    var tmp = false;
}
@using Newtonsoft.Json;
@using System.Net.Http;
@using System.Net.Http.Json;

<div class="container" style="margin-top:3%">
    <h3 style="text-align:center; margin-bottom:2%">@ViewBag.Exam.ExamName Detail</h3>



    <div class=" row" style="margin-top: 5%;">
        <div class="col-sm-2">
        </div>
        <div class="col-sm-4">
            <h5 style="text-align: center;">Number of Tests</h5>
            <canvas id="NoT"
                    style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
        </div>

        <div class="col-sm-4">
            <h5 style="text-align: center;">Number of Reached</h5>
            <canvas id="NoR"
                    style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
        </div>


    </div>


    <div class="row" style="margin-top: 5%;">
        <div class="col">
            <h3 style="text-align: center;">Information</h3>

        </div>
    </div>


    <div class="row" style="margin-top: 2%;">
        <div class="col-sm-4"></div>
        <div class="col" style="font-size: 15pt;">

            <div class="row">
                <div class="col-sm-5">

                    <b>Exam Name:</b>
                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span>@ViewBag.Exam.ExamName</span>
                </div>
            </div>



            <div class="row" style="margin-top:2%">
                <div class="col-sm-5">

                    <b>Start Date:</b>
                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span> @ViewBag.Exam.StartDate</span>
                </div>
            </div>



            <div class="row" style="margin-top:2%">
                <div class="col-sm-5">
                    <b>End Date:</b>

                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span> @ViewBag.Exam.FinishTime </span>
                </div>
            </div>


            <div class="row" style="margin-top:2%">
                <div class="col-sm-5">
                    <b>Number of contestants:</b>

                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span>@ViewBag.Exam.PassPercent %</span>
                </div>
            </div>


            <div class="row" style="margin-top:2%">
                <div class="col-sm-5">
                    <b>Reached:</b>

                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span>@countthi / @countthitotal </span>
                </div>
            </div>


            <div class="row" style="margin-top:2%">
                <div class="col-sm-5">

                    <b>Tested:</b>
                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span> @count / @countthi </span>
                </div>
            </div>


            <div class="row" style="margin-top:2%">
                <div class="col-sm-5">

                    <b>Download file excel report detail:</b>
                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span> <a href="/Admin/Statistique/Report?Examid=@ViewBag.Exam.ExamId">@ViewBag.Exam.ExamName Report.xlsx</a></span>
                </div>
            </div>



        </div>
        <div class="col-sm-3"></div>
    </div>

    <table class="table table-striped " id="table">

        <tr>
            <th>#</th>
            <th>Mail</th>
            <th>Name</th>
            <th>IsTest</th>
            <th>IsPass</th>

            <th>Action</th>
        </tr>
      @for (int j = 0; j < ViewBag.user.Length; j++)
      {


    <tr>
        @{i += 1;}
        <td>@i</td>
        <td>@ViewBag.user[j].Email </td>
        <td>  @ViewBag.user[j].FirstName @ViewBag.user[j].LastName</td>
        <td>
            @foreach (var item in ViewBag.result)
            {
                if (@ViewBag.user[j].Id.Equals(item.IdUser))
                {
                    {
                        tmp = true;
                    }
                    <span class="text-success">Tested</span>
                }


            }
            @if (tmp == false)
            {
                <span class="text-danger">Not Tested</span>
            }
            @{
                tmp = false;
            }

        </td>
        <td>
            @foreach (var item in ViewBag.result)
            {
                if (@ViewBag.user[j].Id.Equals(item.IdUser) && (item.IsPass == true))
                {
                    <span class="text-success">Pass</span>
                }
                else if(@ViewBag.user[j].Id.Equals(item.IdUser) && (item.IsPass != true))
                {
                    <span class="text-danger">Not Pass</span>
                }
            }


        </td>
        <td>
            <a href="/Admin/Statistique/Detailuser?ExamId=@ViewBag.Exam.ExamId&Maill=@ViewBag.user[j].Email"><button class="btn btn-primary">Detail</button></a> 

        </td>
        </tr>
        }
    </table>


</div>


<script>
    $(function () {



          var donutChartCanvas = $('#NoT').get(0).getContext('2d')
        var donutData = {
            labels: [
                'Not Tested',
                'Tested',

            ],
            datasets: [
                {
                    data: [@countthitotal - @countthi, @countthi],
                    backgroundColor: ['#f56954', '#00c0ef'],
                }
            ]
        }
        var donutChart = new Chart(donutChartCanvas, {
            type: 'doughnut',
            data: donutData,
            options: donutOptions
        })


        var donutOptions = {
            maintainAspectRatio: false,
            responsive: true,
        }









        var donutChartCanvas = $('#NoR').get(0).getContext('2d')
        var donutData = {
            labels: [
                'Not Reached',
                'Reached',

            ],
            datasets: [
                {
                    data: [@countthitotal - @count, @count],
                    backgroundColor: ['#f56954', '#00c0ef'],
                }
            ]
        }
        var donutChart = new Chart(donutChartCanvas, {
            type: 'doughnut',
            data: donutData,
            options: donutOptions
        })


        var donutOptions = {
            maintainAspectRatio: false,
            responsive: true,
        }




    })
</script>

<script>



</script>

WebsterWebApp/Areas/Admin/Views/Statistique/Detailuser.cshtml
@{
    ViewData["Title"] = "Exam Result";


    var res = ViewBag.res;
    var total = res.GKScore + res.MathScore + res.TechScore;
    var GKScore = res.GKScore;
    var MathScore = res.MathScore;
    var TechScore = res.TechScore;


}

<script src="~/plugins/chart.js/Chart.min.js"></script>


<div class="container" style="margin-top:7%; min-height:400px">

    <h3 style="text-align: center;">Result Test</h3>


    <div class=" row" style="margin-top: 5%;">
        <div class="col-sm-4">
            <h5 style="text-align: center;">General Knowledge Exam</h5>
            <canvas id="GKtest"
                    style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
        </div>

        <div class="col-sm-4">
            <h5 style="text-align: center;">Math Exam</h5>
            <canvas id="Mathtest"
                    style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
        </div>

        <div class="col-sm-4">
            <h5 style="text-align: center;">Tech Exam</h5>
            <canvas id="Techtest"
                    style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
        </div>

    </div>

    <div class="row" style="margin-top: 5%;">
        <div class="col">
            <h3 style="text-align: center;">Information</h3>

        </div>
    </div>


    <div class="row" style="margin-top: 2%;">
        <div class="col-sm-4"></div>
        <div class="col" style="font-size: 15pt;">

            <div class="row">
                <div class="col-sm-5">

                    <b>Name:</b>
                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span>@ViewBag.name</span>
                </div>
            </div>



            <div class="row">
                <div class="col-sm-5">

                    <b>Mail:</b>
                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span> @ViewBag.mail</span>
                </div>
            </div>



            <div class="row">
                <div class="col-sm-5">
                    <b>Exam Name:</b>

                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span> @ViewBag.examname </span>
                </div>
            </div>


            <div class="row">
                <div class="col-sm-5">
                    <b>GK Score:</b>

                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span>@res.GKScore</span>
                </div>
            </div>


            <div class="row">
                <div class="col-sm-5">
                    <b>GK Time:</b>

                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span>@res.TimeGK s  </span>
                </div>
            </div>


            <div class="row">
                <div class="col-sm-5">

                    <b>Math Score:</b>
                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span>  @res.MathScore </span>
                </div>
            </div>


            <div class="row">
                <div class="col-sm-5">
                    <b>Math Time:</b>

                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span>@res.TimeMath s</span>
                </div>
            </div>


            <div class="row">
                <div class="col-sm-5">

                    <b>Tech Score:</b>
                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span>@res.TechScore</span>
                </div>
            </div>


            <div class="row">
                <div class="col-sm-5">
                    <b>Tech Time:</b>

                </div>
                <div class="col-sm-5" style="text-align:left">
                    <span>@res.TimeTech s</span>
                </div>
            </div>


            <div class="row">
                <div class="col-sm-5">

                    <b>Exam date:</b>
                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span>@res.ExamDate  </span>
                </div>
            </div>


            <div class="row">
                <div class="col-sm-5">
                    <b>Total Score:</b>

                </div>
                <div class="col-sm-7" style="text-align:left">
                    <span> @total /150 </span>
                </div>
            </div>


            <div class="row">
                <div class="col-sm-5">
                    <b>Is Pass::</b>

                </div>
                <div class="col-sm-7" style="text-align:left">
                    @if (res.IsPass)
                    {
                        <span class="text-success" style="font-size:17pt">Pass</span>
                    }
                    else
                    {
                        <span class="text-danger" style="font-size:17pt">Not Pass</span>
                    }
                </div>
            </div>

        </div>
        <div class="col-sm-3"></div>
    </div>


    <div class="row">
        @Html.ActionLink("Back to Detail Exam", "Detail", "Statistique", new { ExamId = @res.ExamId })
    </div>

</div>


<script>
    $(function () {

        var donutChartCanvas = $('#GKtest').get(0).getContext('2d')
        var donutData = {
            labels: [
                'Incorect',
                'Correct',

            ],
            datasets: [
                {
                    data: [50-@GKScore, @GKScore],
                    backgroundColor: ['#f56954', '#00c0ef'],
                }
            ]
        }
        var donutOptions = {
            maintainAspectRatio: false,
            responsive: true,
        }


        //Create pie or douhnut chart
        // You can switch between pie and douhnut using the method below.

        var donutChart = new Chart(donutChartCanvas, {
            type: 'doughnut',
            data: donutData,
            options: donutOptions
        })








        var donutChartCanvas = $('#Mathtest').get(0).getContext('2d')
        var donutData = {
            labels: [
                'Incorect',
                'Correct',

            ],
            datasets: [
                {
                    data: [50 - @MathScore, @MathScore],
                    backgroundColor: ['#f56954', '#00c0ef'],
                }
            ]
        }
        var donutChart = new Chart(donutChartCanvas, {
            type: 'doughnut',
            data: donutData,
            options: donutOptions
        })






        var donutChartCanvas = $('#Techtest').get(0).getContext('2d')
        var donutData = {
            labels: [
                'Incorect',
                'Correct',

            ],
            datasets: [
                {
                    data: [50-@TechScore, @TechScore],
                    backgroundColor: ['#f56954', '#00c0ef'],
                }
            ]
        }

        var donutChart = new Chart(donutChartCanvas, {
            type: 'doughnut',
            data: donutData,
            options: donutOptions
        })


    })
</script>

WebsterWebApp/Areas/Admin/Views/Statistique/Index.cshtml
z@{
    ViewData["Title"] = "Statistique List";

    var data = ViewBag.res;
    var time = ViewBag.date;

}
@using Newtonsoft.Json;
@using System.Net.Http;
@using System.Net.Http.Json;

<div class="container" style="margin-top:3%">
    <h3 style="text-align:center; margin-bottom:2%">Statistique List</h3>
    <div class="row" style="margin-bottom:2%">
        <div class="col-sm-1">  </div>
        <div class="col-sm-9">
            <div class="row">
                <div class="col-sm-3" style="padding-top:1%">
                    <span class="form-label"> From Day:</span>
                </div>
                <div class="col-sm-3">
                    <input type="date" id="fromday"disabled class="form-control" onchange="binding('1')"  placeholder="Enter Exam Name.." />
                </div>
                <div class="col-sm-1">

                </div>
                <div class="col-sm-2" style="padding-top:1%">
                    <span class="form-label"> To Day:</span>
                </div>
                <div class="col-sm-3">
                    <input type="date" id="today" disabled class="form-control" onchange="binding('1')"placeholder="Enter Exam Name.." />

                </div>
            </div>

        </div>
        <div class="col-sm-2">
            <div class="row">

                <div class="col">
                    <input type="checkbox" checked id="checkbox" onclick="eventcheckbox()"/>
                    All Day
                </div>
            </div>

        </div>

    </div>
    <div class="row" style="margin-bottom:2%">
        <div class="col-sm-1">  </div>
        <div class="col-sm-9">
            <div class="row">
                <div class="col-sm-3" style="padding-top:1%">
                    <span class="form-label"> Search by Exam Name:</span>
                </div>
                <div class="col-sm-3">
                    <input type="text" id="searchname" class="form-control" onchange="binding('1')" onkeydown="binding('1')" placeholder="Enter Exam Name.." />
                </div>
                <div class="col-sm-1">

                </div>
                <div class="col-sm-2" style="padding-top:1%">
                    <span class="form-label"> Filter by Status:</span>
                </div>
                <div class="col-sm-3">
                    <select id="searchstatus" class="form-control" onchange="binding('1')">
                        <option value="0">-------Chose-------</option>
                        <option value="Activating">Activating</option>
                        <option value="Not Active">Not Active</option>
                        <option value="Complete">Complete</option>


                    </select>
                </div>
            </div>

        </div>

    </div>

    <table class="table table-striped " id="table">
    </table>


</div>

<pre id="data" hidden>  @JsonConvert.SerializeObject(data)</pre>



<script>

    var data = JSON.parse(document.getElementById("data").innerText);
    var timeconvert = document.getElementById("data");
    timeconvert.parentNode.removeChild(timeconvert);
    console.log(data);
    binding("0");

 

    var status = "";

    function binding(chuoi) {
        vl = false;
        if (document.getElementById("checkbox").checked == true) {
            vl =  false;
        } else {
            vl = true;
        }

        var fromday = Date.parse(document.getElementById("fromday").valueAsDate);
        var today = Date.parse(document.getElementById("today").valueAsDate);
        today += 86400;

        search = "";
        fillter = "0";

        if (chuoi == "1") {
            
            search = document.getElementById("searchname").value;
            fillter = document.getElementById("searchstatus").value;
        }


        var text = `<tr>
                    <th>Exam Id</th>
                    <th>Exam Name</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Status</th>
                    <th>Action</th>
            </tr>`;
        te = "";

        if (search == "" && fillter == "0") {
            

            
            data.forEach(element => {

                var starttime = Date.parse(element.StartDate);
                var endtime = Date.parse(element.FinishTime);
                var currenttime = Date.now();
                //if ((((starttime >= fromday) && (starttime <= today)) || (endtime >= fromday) && ((starttime <= today))) || (vl == false)) {
                    if (((starttime >= fromday) && (starttime < today)) ||  (vl == false)) {


                    if ((currenttime < starttime) && (currenttime < endtime)) {
                        te = `<span class="text-warning" style="font-weight:bold">Not Active</span>`;
                    }
                    if ((currenttime > starttime) && (currenttime > endtime)) {
                        te = `<span class="text-success" style="font-weight:bold">Complete</span>`;

                    }

                    if ((currenttime >= starttime) && (currenttime <= endtime)) {
                        te = `<span class="text-primary" style="font-weight:bold">Activating</span>`;
                    }

                    text += ` <tr>
                                         <td>`+ element.ExamId + `</td>
                                        <td>`+ element.ExamName + `</td>
                                        <td>`+ element.StartDate + `</td>
                                        <td>`+ element.FinishTime + `</td>
                                        <td>`+ te + `</td>
                                        <td>
                                                    <a href="/Admin/Statistique/Detail?ExamId=`+ element.ExamId + `"><input type="button" class="btn btn-info" value="Detail" /></a>


                                        </td>
                                        </tr>`;



                }

            });


            document.getElementById("table").innerHTML = text;
        }


        if (search != "" && fillter == "0") {
            data.forEach(element => {
                if (element.ExamName.toLowerCase().includes(search.toLowerCase())) {

                    var starttime = Date.parse(element.StartDate);
                    var endtime = Date.parse(element.FinishTime);
                    var currenttime = Date.now();


                    if (((starttime >= fromday) && (starttime <= today)) || (vl == false)) {

                    
        

                        if ((currenttime < starttime) && (currenttime < endtime)) {
                            te = `<span class="text-warning" style="font-weight:bold">Not Active</span>`;
                        }
                        if ((currenttime > starttime) && (currenttime > endtime)) {
                            te = `<span class="text-success" style="font-weight:bold">Complete</span>`;

                        }

                        if ((currenttime >= starttime) && (currenttime <= endtime)) {
                            te = `<span class="text-primary" style="font-weight:bold">Activating</span>`;
                        }

                        text += ` <tr>
                                                 <td>`+ element.ExamId + `</td>
                                                <td>`+ element.ExamName + `</td>
                                                <td>`+ element.StartDate + `</td>
                                                <td>`+ element.FinishTime + `</td>
                                                <td>`+ te + `</td>
                                                <td>
                                                    <a href="/Admin/Statistique/Detail?ExamId=`+ element.ExamId + `"><input type="button" class="btn btn-info" value="Detail" /></a>


                                                </td>
                                                </tr>`;

                    }
                }
            });


            document.getElementById("table").innerHTML = text;
        }


        if ( fillter != "0") {
            data.forEach(element => {
                if (element.ExamName.toLowerCase().includes(search))  {


                  
                    var starttime = Date.parse(element.StartDate);
                    var endtime = Date.parse(element.FinishTime);
                    var currenttime = Date.now();

                    if (((starttime >= fromday) && (starttime <= today)) || (vl == false)) {
                        if ((currenttime < starttime) && (currenttime < endtime)) {
                            te = `<span class="text-warning" style="font-weight:bold">Not Active</span>`;
                            status = "Not Active";
                        }
                        if ((currenttime > starttime) && (currenttime > endtime)) {
                            te = `<span class="text-success" style="font-weight:bold">Complete</span>`;
                            status = "Complete";

                        }

                        if ((currenttime >= starttime) && (currenttime <= endtime)) {
                            te = `<span class="text-primary" style="font-weight:bold">Activating</span>`;
                            status = "Activating";

                        }
                        if (status == fillter) {

                            text += ` <tr>
                                                 <td>`+ element.ExamId + `</td>
                                                <td>`+ element.ExamName + `</td>
                                                <td>`+ element.StartDate + `</td>
                                                <td>`+ element.FinishTime + `</td>
                                                <td>`+ te + `</td>
                                                <td>
                                                    <a href="/Admin/Statistique/Detail?ExamId=`+ element.ExamId + `"><input type="button" class="btn btn-info" value="Detail" /></a>

                                                </td>
                                                </tr>`;
                        }
                    }

                }
            });


            document.getElementById("table").innerHTML = text;
        }
    }


</script>
<script>

    function eventcheckbox() {
        document.getElementById("fromday").valueAsDate = new Date();
        document.getElementById("today").valueAsDate = new Date();

        stt = document.getElementById("checkbox").checked;
        document.getElementById("fromday").disabled = true;

        document.getElementById("today").disabled = true;
        if (stt == true) {
            binding("0");
        } else {
            document.getElementById("fromday").disabled = false;

            document.getElementById("today").disabled = false;
            binding('1')
        } 
        
    }
</script>