WebsterWebApp/Areas/Admin/Models/Question.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace WebsterWebApp.Areas.Admin.Models
{
    [Table("tb_Question")]
    public class Question
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int QuestionId { get; set; }

        [Required(ErrorMessage = "Subject is required!")]
        public String Subject { get; set; }

        public String QuestionTitle { get; set; }

        [Required(ErrorMessage = "Question type is required!")]
        public bool QuestionType { get; set; }

        public String Photo { get; set; }
    }
}

WebsterWebApp/Areas/Admin/Controllers/QuestionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using OfficeOpenXml.Drawing;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

using WebsterWebApp.Areas.Admin.Models;

namespace WebsterWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class QuestionController : Controller
    {

        private readonly Data.ApplicationDbContext _db;

        public QuestionController(Data.ApplicationDbContext db)
        {
            this._db = db;
        }

        public IActionResult IndexCharts()
        {
            int gkQuantity = _db.Questions.Where(q => q.Subject == "General Knowledge").Count();
            int mathQuantity = _db.Questions.Where(q => q.Subject == "Mathematics").Count();
            int techQuantity = _db.Questions.Where(q => q.Subject == "Technical").Count();
            List<int> data = new List<int> { gkQuantity, mathQuantity, techQuantity };
            return  Json(new { JsonList = data });
        }

        public IActionResult Index(String subject, String questionTitle, int pg = 1)
        {
            if (HttpContext.Session.GetString("_msg") != null)
            {
                ViewBag.msg = HttpContext.Session.GetString("_msg");
            }
            else
            {
                ViewBag.msg = "";
            }
            TempData["subject"] = new List<String> { "General Knowledge", "Mathematics", "Technical" };
            var model = _db.Questions.ToList();
            const int pageSize = 10;
            if (pg < 1)
            {
                pg = 1;
            }
            if (String.IsNullOrEmpty(subject) && String.IsNullOrEmpty(questionTitle))
            {  
                int modelCount = model.Count;
                var pager = new Pager(modelCount, pg, pageSize);
                int modelSkip = (pg - 1) * pageSize;
                model = model.Skip(modelSkip).Take(pager.PageSize).ToList();
                ViewBag.Pager = pager;
                return View(model);
            }
            else if (!String.IsNullOrEmpty(subject) && String.IsNullOrEmpty(questionTitle))
            {
                ViewBag.optionSubject = subject;
                model = model.ToList().FindAll(m => m.Subject.ToUpper().Equals(subject.ToUpper()));
                int modelCount = model.Count;
                var pager = new Pager(modelCount, pg, pageSize);
                int modelSkip = (pg - 1) * pageSize;
                model = model.Skip(modelSkip).Take(pager.PageSize).ToList();
                ViewBag.Pager = pager;
                return View(model);
            }
            else if(String.IsNullOrEmpty(subject) && !String.IsNullOrEmpty(questionTitle))
            {
                model = model.ToList().FindAll(m => m.QuestionTitle.ToUpper().Contains(questionTitle.ToUpper()));
                int modelCount = model.Count;
                var pager = new Pager(modelCount, pg, pageSize);
                int modelSkip = (pg - 1) * pageSize;
                model = model.Skip(modelSkip).Take(pager.PageSize).ToList();
                ViewBag.Pager = pager;
                return View(model);
            }
            else
            {
                ViewBag.optionSubject = subject;
                model = model.ToList().FindAll(m => m.Subject.ToUpper().Equals(subject.ToUpper()) 
                && m.QuestionTitle.ToUpper().Contains(questionTitle.ToUpper()));
                int modelCount = model.Count;
                var pager = new Pager(modelCount, pg, pageSize);
                int modelSkip = (pg - 1) * pageSize;
                model = model.Skip(modelSkip).Take(pager.PageSize).ToList();
                ViewBag.Pager = pager;
                return View(model);
            }
        }

        [HttpPost]
        public JsonResult AutoComplete(String prefix)
        {
            var questions = (from question in _db.Questions
                             where question.QuestionTitle.StartsWith(prefix)
                             select new
                             {
                                 label = question.QuestionTitle,
                             }).ToList();

            return Json(questions);
        }

        public IActionResult BatchQuestionUpload()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> BatchQuestionUpload(IFormFile batchQuestions)
        {
            if (batchQuestions?.Length > 0)
            {
                var stream = batchQuestions.OpenReadStream();
                try
                {
                    using (var package = new ExcelPackage(stream))
                    {
                        ExcelWorksheet worksheet = package.Workbook.Worksheets.First();
                        int rowCount = worksheet.Dimension.Rows;

                        String tmp = "0";
                        List<Question> questions = new List<Question>();
                        List<Answer> answers = new List<Answer>();
                        for (int row = 2; row <= rowCount; row++)
                        {
                            if (worksheet.Cells[row, 1].Value?.ToString() == "Default")
                            {
                                tmp = "0";
                                String subject = worksheet.Cells[row, 2].Value?.ToString();
                                String title = worksheet.Cells[row, 3].Value?.ToString();
                                String photoQuestion = worksheet.Cells[row, 4].Value?.ToString();
                                String type = worksheet.Cells[row, 5].Value?.ToString();
                                List<String> sub = new List<string> { "General Knowledge", "Mathematics", "Technical" };

                                if (subject == null || title == null || type == null ||
                                    subject != "General Knowledge" && subject != "Mathematics" && subject != "Technical")
                                {
                                    tmp = "1";
                                }

                                Question question = new Question()
                                {
                                    Subject = subject,
                                    QuestionTitle = title,
                                    Photo = photoQuestion,
                                    QuestionType = type == "QuestionHasOneAnswer" ? true : false,
                                };

                                if (tmp == "0")
                                {
                                    questions.Add(question);
                                }
                                else
                                {
                                    ViewBag.msg = "upload fail!";
                                    return View();
                                }

                                String firstAnswer = worksheet.Cells[row, 6].Value?.ToString();
                                String photoFirstAnswer = worksheet.Cells[row, 7].Value?.ToString();
                                String secondAnswer = worksheet.Cells[row, 8].Value?.ToString();
                                String photoSecondAnswer = worksheet.Cells[row, 9].Value?.ToString();
                                String thirdAnswer = worksheet.Cells[row, 10].Value?.ToString();
                                String photoThirdAnswer = worksheet.Cells[row, 11].Value?.ToString();
                                String fourthAnswer = worksheet.Cells[row, 12].Value?.ToString();
                                String photoFourthAnswer = worksheet.Cells[row, 13].Value?.ToString();
                                String answerCorrect = worksheet.Cells[row, 14].Value?.ToString();
                                if (firstAnswer == null || secondAnswer == null || thirdAnswer == null || fourthAnswer == null || answerCorrect == null)
                                {
                                    tmp = "1";
                                }

                                if (type == "QuestionHasOneAnswer")
                                {
                                    Answer answer1 = new Answer()
                                    {
                                        AnswerContent = firstAnswer,
                                        Photo = photoFirstAnswer,
                                        IsCorrectAnswer = answerCorrect == "A" ? true : false,
                                    };

                                    Answer answer2 = new Answer()
                                    {
                                        AnswerContent = secondAnswer,
                                        Photo = photoSecondAnswer,
                                        IsCorrectAnswer = answerCorrect == "B" ? true : false,
                                    };

                                    Answer answer3 = new Answer()
                                    {
                                        AnswerContent = thirdAnswer,
                                        Photo = photoThirdAnswer,
                                        IsCorrectAnswer = answerCorrect == "C" ? true : false,
                                    };

                                    Answer answer4 = new Answer()
                                    {
                                        AnswerContent = fourthAnswer,
                                        Photo = photoFourthAnswer,
                                        IsCorrectAnswer = answerCorrect == "D" ? true : false,
                                    };

                                    if (tmp == "0")
                                    {
                                        answers.Add(answer1);

WebsterWebApp/Areas/Admin/Views/Question/BatchQuestionUpload.cshtml
@{
    ViewData["Title"] = "Upload file excel";
    Layout = "_LayoutQuestion";
}

<h4><b style="color: limegreen">Upload New Question</b></h4>
<br />

<form asp-action="BatchQuestionUpload" asp-controller="Question" method="post" enctype="multipart/form-data">
    <input type="file" name="batchQuestions" id="batchQuestions" onchange="validationBatchQuestions()" class="form-label" />
    <br />
    <br />
    <input type="submit" value="Upload" class="btn btn-success" />
</form>

<hr />

<p class="text-danger">@ViewBag.msg</p>
<br />
<div>
    <p>File Excel must be format like this. If you want to upload image then you drag and drop image into folder images/QA</p>
    <p><a href="~/questionList.xlsx" style="cursor: pointer; text-decoration: auto">Download inputed form</a></p>
    <p><a href="~/uploadform.xlsx" style="cursor: pointer; text-decoration: auto">Download empty form</a></p>
    <a href="~/images/QA/Untitled5.png" data-lightbox="~/images/QA/Untitled5.png"><img src="~/images/QA/Untitled5.png" width="500" /></a>
    &nbsp; &nbsp; &nbsp; &nbsp;
    <a href="~/images/QA/Untitled7.png" data-lightbox="~/images/QA/Untitled7.png"><img src="~/images/QA/Untitled7.png" width="500" /></a>
</div>

<div>
    <a style="cursor:pointer;color: deeppink;" onclick="history.back()">Back to List</a>
</div>

<script>
    function validationBatchQuestions() {
        var fileInput = document.getElementById('batchQuestions');
        var filePath = fileInput.value;

        var allowedExtensions =
            /(\.xlsx|\.xls)$/i;

        if (!allowedExtensions.exec(filePath)) {
            alert('Must be .xlsx, .xls file!');
            fileInput.value = '';
            return false;
        } else {
            return true;
        }
    }
</script>

WebsterWebApp/Areas/Admin/Views/Question/Deta1ls.cshtml
@model WebsterWebApp.Areas.Admin.Models.Question

@{
    ViewData["Title"] = "Details Question";
    Layout = "_LayoutQuestion";
}

<h4>Details Question</h4>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.QuestionTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.QuestionTitle)
        </dd>
        <dt class="col-sm-2">
            Image Question
        </dt>
        <dd class="col-sm-10">
            @if (Model.Photo == null)
            {
                <p>Empty</p>

            }
            else
            {
                <img src="~/@Url.Content(Model.Photo)" width="120" />
            }
        </dd>
        <dt class="col-sm-2">
            A.
        </dt>
        <dd class="col-sm-10">
            @ViewBag.firstAnswerContent
        </dd>
        <dt class="col-sm-2">
            <label>Image Answer A</label>
        </dt>
        <dd class="col-sm-10">
            @if (@ViewBag.photoFirstAns == null)
            {
                <p>Empty</p>

            }
            else
            {
                <img src="~/@ViewBag.photoFirstAns" width="120" />
            }
        </dd>
        <dt class="col-sm-2">
        </dt>
        <dd class="col-sm-10">
            ---------------------------
        </dd>
        <dt class="col-sm-2">
            B.
        </dt>
        <dd class="col-sm-10">
            @ViewBag.secondAnswerContent
        </dd>
        <dt class="col-sm-2">
            Image Answer B
        </dt>
        <dd class="col-sm-10">
            @if (@ViewBag.photoSecondAns == null)
            {
                <p>Empty</p>

            }
            else
            {
                <img src="~/@ViewBag.photoSecondAns" width="120" />
            }
        </dd>
        <dt class="col-sm-2">
            Question type
        </dt>
        <dd class="col-sm-10">
            @{String questionType = Model.QuestionType ? "One Answer" : "Many Answer";}
            @questionType
        </dd>
        <dt class="col-sm-2">
            Correct Answer
        </dt>
        <dd class="col-sm-2">
            
            <select name="isCorrectAnswer" disabled>
                @foreach (var item in ViewBag.yesnoAnswer)
                {
                    if (ViewBag.CorrectAnswer1 == true && item == "Yes")
                    {
                        <option value="@item" selected>@item</option>
                    }
                    else if (ViewBag.CorrectAnswer2 == true && item == "No")
                    {
                        <option value="@item" selected>@item</option>
                    }
                    else
                    {
                        <option value="@item">@item</option>
                    }
                }
            </select>   
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.QuestionId">Edit</a> &nbsp;
    <a style="cursor:pointer;color: deeppink;" onclick="history.back()">Back to List</a>
</div>

WebsterWebApp/Areas/Admin/Views/Question/Details.cshtml
@model WebsterWebApp.Areas.Admin.Models.Question

@{
    ViewData["Title"] = "Details Question";
    Layout = "_LayoutQuestion";
}

<h4>Details Question</h4>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.QuestionTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.QuestionTitle)
        </dd>
        <dt class="col-sm-2">
            Image Question
        </dt>
        <dd class="col-sm-10">
            @if (Model.Photo == null)
            {
                <p>Empty</p>

            }
            else
            {
                <img src="~/@Url.Content(Model.Photo)" width="120" />
            }
        </dd>
        <dt class="col-sm-2">
            A.
        </dt>
        <dd class="col-sm-10">
            @ViewBag.firstAnswerContent
        </dd>
        <dt class="col-sm-2">
            <label>Image Answer A</label>
        </dt>
        <dd class="col-sm-10">
            @if (@ViewBag.photoFirstAns == null)
            {
                <p>Empty</p>

            }
            else
            {
                <img src="~/@ViewBag.photoFirstAns" width="120" />
            }
        </dd>
        <dt class="col-sm-2">
        </dt>
        <dd class="col-sm-10">
            ---------------------------
        </dd>
        <dt class="col-sm-2">
            B.
        </dt>
        <dd class="col-sm-10">
            @ViewBag.secondAnswerContent
        </dd>
        <dt class="col-sm-2">
            Image Answer B
        </dt>
        <dd class="col-sm-10">
            @if (@ViewBag.photoSecondAns == null)
            {
                <p>Empty</p>

            }
            else
            {
                <img src="~/@ViewBag.photoSecondAns" width="120" />
            }
        </dd>
        <dt class="col-sm-2">
        </dt>
        <dd class="col-sm-10">
            ---------------------------
        </dd>
        <dt class="col-sm-2">
            C.
        </dt>
        <dd class="col-sm-10">
            @ViewBag.thirdAnswerContent
        </dd>
        <dt class="col-sm-2">
            Image Answer C
        </dt>
        <dd class="col-sm-10">
            @if (@ViewBag.photoThirdAns == null)
            {
                <p>Empty</p>
            }
            else
            {
                <img src="~/@ViewBag.photoThirdAns" width="120" />
            }
        </dd>
        <dt class="col-sm-2">
        </dt>
        <dd class="col-sm-10">
            ---------------------------
        </dd>
        <dt class="col-sm-2">
            D.
        </dt>
        <dd class="col-sm-10">
            @ViewBag.fourthAnswerContent
        </dd>
        <dt class="col-sm-2">
            Image Answer D
        </dt>
        <dd class="col-sm-10">
            @if (@ViewBag.photoFourthAns == null)
            {
                <p>Empty</p>
            }
            else
            {
                <img src="~/@ViewBag.photoFourthAns" width="120" />
            }
        </dd>
        <dt class="col-sm-2">
            Question type
        </dt>
        <dd class="col-sm-10">
            @{String questionType = Model.QuestionType ? "One Answer" : "Many Answer";}
            @questionType
        </dd>
        <dt class="col-sm-2">
            Correct Answer
        </dt>
        <dd class="col-sm-10">
            @if (Model.QuestionType == false)
            {
                @if (ViewBag.CorrectAnswer1 == true)
                {
                    <label>Answer A</label>
                    <input type="checkbox" name="CorrectAnswer1" value="true" disabled="disabled" checked />
                }
                else
                {
                    <label>Answer A</label>
                    <input type="checkbox" name="CorrectAnswer1" value="true" disabled="disabled" />
                }
                <br />
                @if (ViewBag.CorrectAnswer2 == true)
                {
                    <label>Answer B</label>
                    <input type="checkbox" name="CorrectAnswer2" value="true" disabled="disabled" checked />
                }
                else
                {
                    <label>Answer B</label>
                    <input type="checkbox" name="CorrectAnswer2" value="true" disabled="disabled" />
                }
                <br />
                @if (ViewBag.CorrectAnswer3 == true)
                {
                    <label>Answer C</label>
                    <input type="checkbox" name="CorrectAnswer3" value="true" disabled="disabled" checked />
                }
                else
                {
                    <label>Answer C</label>
                    <input type="checkbox" name="CorrectAnswer3" value="true" disabled="disabled" />
                }
                <br />
                @if (ViewBag.CorrectAnswer4 == true)
                {
                    <label>Answer D</label>
                    <input type="checkbox" name="CorrectAnswer4" value="true" disabled="disabled" checked />
                }
                else
                {
                    <label>Answer D</label>
                    <input type="checkbox" name="CorrectAnswer4" value="true" disabled="disabled" />
                }
            }
            else
            {
                <select name="isCorrectAnswer" disabled>
                    @foreach (var item in ViewBag.selectAnswer)
                    {
                        if (ViewBag.CorrectAnswer1 == true)
                        {
                            <option value="@item" selected>Answer A</option>
                        }
                        else if (ViewBag.CorrectAnswer2 == true)
                        {
                            <option value="@item" selected>Answer B</option>
                        }
                        else if (ViewBag.CorrectAnswer3 == true)
                        {
                            <option value="@item" selected>Answer C</option>
                        }
                        else if (ViewBag.CorrectAnswer4 == true)
                        {
                            <option value="@item" selected>Answer D</option>
                        }
                        else
                        {
                            <option value="@item">@item</option>
                        }

                    }
                </select>
            }
        </dd>
    </dl>
</div>


<div>
    <a asp-action="Edit" asp-route-id="@Model.QuestionId">Edit</a> &nbsp;
    <a style="cursor:pointer;color: deeppink;" onclick="history.back()">Back to List</a>
</div>

WebsterWebApp/Areas/Admin/Views/Question/Index.cshtml
@model IEnumerable<WebsterWebApp.Areas.Admin.Models.Question>

@{

    ViewData["Title"] = "Question List";
    Layout = "_LayoutQuestion";
    WebsterWebApp.Areas.Admin.Models.Pager pager = new WebsterWebApp.Areas.Admin.Models.Pager();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

<h4>Question List</h4>

<p class="text-danger">@ViewBag.msg</p>

<a asp-action="Create"><b style="color:dodgerblue">Create New Question</b></a>
&nbsp; or &nbsp;
<a asp-action="BatchQuestionUpload"><b style="color:dodgerblue">Upload New Question</b></a>

<hr />

<div>
    @section Scripts{
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        @*<script src="~/js/loader.js"></script>*@
        <script type="text/javascript">
            google.charts.load('current', { 'packages': ['corechart'] });
            google.charts.setOnLoadCallback(drawOnLoad);
            function drawOnLoad() {
                $(function () {
                    $.ajax({
                        type: 'GET',
                        url: '/Admin/Question/IndexCharts',
                        success: function (chartsdata) {
                            var Data = chartsdata.jsonList;
                            var data = new google.visualization.DataTable();
                            data.addColumn('string', 'Subject');
                            data.addColumn('number', 'Question Quantity');

                            data.addRows([
                                ['General Knowledge', Data[0]],
                                ['Mathematics', Data[1]],
                                ['Technical', Data[2]],
                            ]);

                            var piechart = new google.visualization.PieChart(document.getElementById('piediv'));
                            piechart.draw(data, {
                                title: "question per subject",
                                position: "top",
                                fontsize: "15px"
                            });

                            var barchart = new google.visualization.BarChart(document.getElementById('bardiv'));
                            barchart.draw(data, {
                                title: "question per subject",
                                width: "450",
                                height: "350"
                            });
                        }
                    });
                })
            }
        </script>
    }
    <table align="center">
        <tr>
            <td>
                <div id="piediv" style="width:500px; height: 350px; border:2px solid red" ;></div>
            </td>
            <td>
                <div id="bardiv" style="border:2px solid red" ;></div>
            </td>
        </tr>
    </table>
</div>

<br />

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.0.min.js" type="text/javascript"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/jquery-ui.min.js" type="text/javascript"></script>
<link href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/themes/blitzer/jquery-ui.css" rel="Stylesheet" type="text/css" />

<script>
    $(function () {
        $("#txtQuestion").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '/Admin/Question/AutoComplete/',
                    data: { "prefix": request.term },
                    type: "POST",
                    success: function (data) {
                        response($.map(data, function (item) {
                            return item;
                        }))
                    },
                    error: function (response) {
                        alert(response.responseText)
                    },
                    failure: function (response) {
                        alert(response.responseText)
                    }
                });
            },
            minLength: 1
        });
    });
</script>

<form asp-action="Index" method="post">
    <select name="subject" onchange="check()">
        @if (ViewBag.optionSubject == null)
        {
            <option value="">All</option>
            @foreach (var item in TempData["subject"] as List<String>)
            {
                <option value="@item">@item</option>
            }
        }
        else
        {
            <option value="">All</option>
            foreach (var item in TempData["subject"] as List<String>)
            {
                if (item == ViewBag.optionSubject)
                {
                    <option value="@item" selected>@item</option>
                }
                else
                {
                    <option value="@item">@item</option>
                }
            }
        }
    </select>
    &nbsp;
    <input type="text" name="questionTitle" id="txtQuestion" placeholder="Enter question title" />
    <input type="submit" id="_Filter" value="Filter" class="btn-primary" />
</form>

<br />

<div>
    <table class="table" cellspacing="0" cellpadding="0">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Subject)
                </th>
                <th>
                    Question title
                </th>
                <th>
                    Question type
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Photo)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                String questionType = item.QuestionType ? "One Answer" : "Many Answer";
                String title;

                @if (item.QuestionTitle.Length >= 22)
                {
                    title = item.QuestionTitle.Substring(0, 22) + "...";
                }
                else
                {
                    title = item.QuestionTitle;
                }
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Subject)
                    </td>
                    <td>
                        @title
                    </td>
                    <td>
                        @questionType
                    </td>
                    <td>
                        @if (item.Photo == null)
                        {
                            <p>Empty</p>
                        }
                        else
                        {
                            <img src="~/@item.Photo" width="120" />
                        }
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.QuestionId" class="btn btn-success">Edit</a> &nbsp;
                        <a asp-action="Details" asp-route-id="@item.QuestionId" class="btn btn-info">Details</a> &nbsp;
                        <a asp-action="Delete" onclick="ConfirmDelete()" asp-route-id="@item.QuestionId" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<hr />

<div class="container" style="min-height: 50px;">
    @if (pager.TotalPages > 0)
    {
        <ul class="pagination justify-content-end" style="float: right;">
            @if (pager.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Question" asp-action="Index" asp-route-pg="1">First</a>
                </li>
                <li>
                    <a class="page-link" asp-controller="Question" asp-action="Index"
                       asp-route-pg="@(pager.CurrentPage - 1)">Previous</a>
                </li>
            }
            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
            {
                <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-controller="Question" asp-action="Index" asp-route-pg="@pge"> @pge </a>
                </li>
            }
            @if (pager.CurrentPage < pager.TotalPages)
            {
                <li>
                    <a class="page-link" asp-controller="Question" asp-action="Index"
                       asp-route-pg="@(pager.CurrentPage + 1)">Next</a>
                </li>
                <li>
                    <a class="page-link" asp-controller="Question" asp-action="Index"
                       asp-route-pg="@(pager.TotalPages)">Last</a>
                </li>
            }
        </ul>
    }
</div>

<script>
    function check() {
        document.getElementById("_Filter").click() = "true";
    }
</script>

<script>

    function ConfirmDelete() {
        if (confirm("Are you sure ?")) {
            return true;
        } else {
            event.preventDefault();
        }
    }
</script>